name: Publish To NuGet

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Create NuGet Package
        run: dotnet pack -c Release -o NuGet ./src/Aocl
      - name: Publish NuGet Package
        run: dotnet nuget push --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json ./NuGet/Aocl*.nupkg
